#!/bin/bash
#date: August 28, 2015
#author: Andreas Isaak
#website: https://andreas.isaak.li
#email: andreas@isaak.li

# Minecraft Server Installer – A lightweight script which guides you through the installation of a Minecraft server
# Copyright (C) 2015  Andreas Isaak

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

downloading() {
clear
echo "Downloading server software…"
}
makedir() {
clear
read -p "In what directory would you like the Minecraft server to be installed? Specify a directory [$PWD/$server]: " path
clear
if [ -z "$path" ]
	then 
        mkdir $server && cd $server
	else
        mkdir $path && cd $path
fi
}
clear
echo -e "Checking dependencies, this may take a while…\nYou can skip this by pressing CTRL + C if you already have done an installation on this system before."
sudo apt-get update >/dev/null 2>&1 && sudo apt-get -y install wget default-jre screen >/dev/null 2>&1
if [ ! -e /usr/bin/jq ]
    then
        architecture=`uname -m`
        if [ "$architecture" == "x86_64" ]
            then
                wget http://stedolan.github.io/jq/download/linux64/jq >/dev/null 2>&1
            else
                wget http://stedolan.github.io/jq/download/linux32/jq >/dev/null 2>&1
        fi
        unset architecture
        chmod +x ./jq
        sudo mv jq /usr/bin
fi
clear
echo -e "This script will guide you through the installation of a Minecraft server. You can abort the installation by pressing CTRL + C at anytime.\n\nDo you accept the Minecraft EULA? You can read it here: https://account.mojang.com/documents/minecraft_eula" && read -p "[y/N]: " eula
case "$eula" in
    y|Y|yes|Yes|ye|Ye|yeh|Yeh)
    ;;
    *) echo "Sorry, if you want to create a Minecraft server you must accept the Minecraft EULA."
    exit
    ;;
esac
while [[ ! $maxram =~ ^[0-9]+$ ]]; do
    clear
    read -p "Please specify the maximum amount of RAM in megabytes the server may reserve. It is not recommended to specifiy more than 75% of the system's available RAM: " maxram
done
minram=$maxram+1
while [[ $minram -gt $maxram ]]; do
    minram=""
    while [[ ! $minram =~ ^[0-9]+$ ]]; do
        clear
        read -p "Please specify the minimum amount of RAM in megabytes the server may reserve. It must not be larger than the maximum amount of RAM: " minram
    done
done
condition=true
while $condition; do
clear
echo "1. Vanilla"
echo "2. CraftBukkit"
echo -e "3. Spigot\n"
read -p "Please select a server to install: " server
    case "$server" in
	    1|v|V|vanilla|Vanilla)
    condition=false
    server=vanilla
    makedir
    clear
    echo "Fetching server versions…"
    wget http://s3.amazonaws.com/Minecraft.Download/versions/versions.json >/dev/null 2>&1
    temp=`cat versions.json | jq '.latest.release'`
    version="${temp:1:${#temp}-2}"
    rm versions.json
    downloading
    wget https://s3.amazonaws.com/Minecraft.Download/versions/${version}/minecraft_server.${version}.jar -O minecraft_server.jar >/dev/null 2>&1
    unset -v temp version
	    ;;
	    2|c|C|b|B|craftbukkit|CraftBukkit|bukkit|Bukkit)
    condition=false
    server=craftbukkit
    makedir
    downloading
    wget http://getspigot.org/spigot18/craftbukkit_server.jar -O minecraft_server.jar >/dev/null 2>&1
	    ;;
	    3|s|S|spigot|Spigot)
    condition=false
    server=spigot
    makedir
    downloading
    wget http://getspigot.org/spigot18/spigot_server.jar -O minecraft_server.jar >/dev/null 2>&1
	    ;;
	    *) echo -e "Invalid selection."
	    ;;
    esac
done
echo screen -A -m -d -S $server java -Xmx${maxram}M -Xms${minram}M -jar minecraft_server.jar nogui > start.sh && chmod +x start.sh
unset -v path maxram minram
echo 'screen -S minecraft -p 0 -X stuff "$(printf "stop\r")"' > stop.sh && chmod +x stop.sh
echo 'eula=true' > eula.txt
clear
echo -e "The installation is done. Would you like to start your Minecraft server now? You can start it later with the pre-generated start script." && read -p "[Y/n]" start
case "$start" in
    ""|y|Y|yes|Yes|ye|Ye|yeh|Yeh) ./start.sh
    echo -e "\nYour Minecraft server is starting now, have fun! You can switch into it's console by typing \"screen -r ${server}\".\n"
    ;;
    *|n|N|no|No|nah|Nah) echo -e "\nThat's it!\n"
    ;;
esac
